import mongoose from 'mongoose';
import CuttingSubModelSchema from './CuttingSubModelSchema.js';

const CuttingSchema = new mongoose.Schema({
    model: { type: String, required: true, default: '*' },
    technicalDescription: { type: String, required: true, default: '*' },
    detailedTechnicalDescription: { type: String, required: true, default: '*' },
    functions: { type: String, default: '*' },
    needleType: { type: String, default: '*' },
    needleGauge: { type: String, default: '*' },
    needleNo: { type: String, default: '*' },
    needleBarStroke: { type: String, default: '*' },
    threadNo: { type: String, default: '*' },
    doubleNeedleStitchLength: { type: String, default: '*' },
    stitchLengthRange: { type: String, default: '*' },
    stitchWidthRange: { type: String, default: '*' },
    liftHeightRange: { type: String, default: '*' },
    isSuitableForLightMaterial: { type: Boolean, default: false },
    isSuitableForMediumMaterial: { type: Boolean, default: false },
    isSuitableForHeavyMaterial: { type: Boolean, default: false },
    weight: { type: String, default: '*' },
    packingSize: { type: String, default: '*' },
    differentialRatio: { type: String, default: '*' },
    speedInRPM: { type: String, default: '*' },
    quantityOfStandardPattern: { type: String, default: '*' },
    rateOfMagnifyAndShrink: { type: String, default: '*' },
    powerOfMotorsOutputting: { type: String, default: '*' },
    power: { type: String, default: '*' },
    cutterSize: { type: String, default: '*' },
    buttonDiameter: { type: String, default: '*' },
    stitchWidth: { type: String, default: '*' },
    dot: { type: String, default: '*' },
    plug: { type: String, default: '*' },
    buttonHoleWidth: { type: String, default: '*' },
    cuttingHeight: { type: String, default: '*' }, // Adjusted field name to camelCase
    voltage: { type: String, default: '*' },
    frequency: { type: String, default: '*' },
    pipingCuttingWidth: { type: String, default: '*' },
    tableSize: { type: String, default: '*' },
    armSize: { type: String, default: '*' },
    knifeSize: { type: String, default: '*' },
    netWeight: { type: String, default: '*' },
    powerSupply: { type: String, default: '*' },
    ratedOutput: { type: String, default: '*' },
    temperature: { type: String, default: '*' },
    pressure: { type: String, default: '*' },
    beltSpeed: { type: String, default: '*' },
    heatingTime: { type: String, default: '*' },
    fusingWidth: { type: String, default: '*' },
    dimension: { type: String, default: '*' },
    cuttingLength: { type: String, default: '*' },
    maximumCutting: { type: String, default: '*' },
    cuttingSpeed: { type: String, default: '*' },
    maximumBladeTemperature: { type: String, default: '*' },
    powerKw: { type: String, default: '*' },
    packageSizeLxWxH: { type: String, default: '*' },
    recommendedAirPressure: { type: String, default: '*' },
    oil: { type: String, default: '*' },
    image: { type: String, default: '*' },
    series: { type: mongoose.Schema.Types.ObjectId, ref: 'Series', required: true },
    subModels: { type: [CuttingSubModelSchema], default: [] }
});

const CuttingModel = mongoose.model('CuttingSeries', CuttingSchema);
export default CuttingModel;
