import mongoose from 'mongoose';

const SpecialSeriesSubModelSchema = new mongoose.Schema({
    model: { type: String, required: true, default: '*' },
    technicalDescription: { type: String, required: true, default: '*' },
    detailedTechnicalDescription: { type: String, required: true, default: '*' },
    functions: { type: String, default: '*' },
    needleType: { type: String, default: '*' },
    needleFeed: { type: String, default: '*' },
    needleGauge: { type: String, default: '*' },
    needleNo: { type: String, default: '*' },
    needleBarStroke: { type: String, default: '*' },
    threadNo: { type: String, default: '*' },
    doubleNeedleStitchLength: { type: String, default: '*' },
    stitchLengthRange: { type: String, default: '*' },
    stitchWidthRange: { type: String, default: '*' },
    liftHeightRange: { type: String, default: '*' },
    hasAutoThreadTrimmer: { type: Boolean, default: false },
    hasAutoLift: { type: Boolean, default: false },
    isSuitableForLightMaterial: { type: Boolean, default: false },
    isSuitableForMediumMaterial: { type: Boolean, default: false },
    isSuitableForHeavyMaterial: { type: Boolean, default: false },
    horizontalHook: { type: Boolean, default: false },
    verticalHook: { type: Boolean, default: false },
    weight: { type: String, default: '*' },
    packingSize: { type: String, default: '*' },
    differentialRatio: { type: String, default: '*' },
    speedInRPM: { type: String, default: '*' },
    quantityOfStandardPattern: { type: String, default: '*' },
    rateOfMagnifyAndShrink: { type: String, default: '*' },
    powerOfMotorsOutputting: { type: String, default: '*' },
    power: { type: String, default: '*' },
    voltage: { type: String, default: '*' },
    frequency: { type: String, default: '*' },
    headPackage: { type: String, default: '*' },
    rackPackage: { type: String, default: '*' },
    GWhead: { type: String, default: '*' },
    rackGW: { type: String, default: '*' },
    cutterSize: { type: String, default: '*' },
    zigzagSewingLength: { type: String, default: '*' },
    buttonDiameter: { type: String, default: '*' },
    buttonStitch: { type: String, default: '*' },
    stirches: { type: String, default: '*' },
    sewingArea: { type: String, default: '*' },
    sizeOfButtonsThatCanBeSewn: { type: String, default: '*' },
    clothFeedingMethod: { type: String, default: '*' },
    pitch: { type: String, default: '*' },
    maximumNumberOfStitches: { type: String, default: '*' },
    presserFootLiftMethod: { type: String, default: '*' },
    liftingAmountOfPresserFoot: { type: String, default: '*' },
    buttonClampLift: { type: String, default: '*' },
    useHook: { type: String, default: '*' },
    wipingDevice: { type: String, default: '*' },
    threadCuttingDevice: { type: String, default: '*' },
    dataStorageMethod: { type: String, default: '*' },
    externalDataStorageMedium: { type: String, default: '*' },
    numberOfCyclicPrograms: { type: String, default: '*' },
    storingData: { type: String, default: '*' },
    motors: { type: String, default: '*' },
    powerSupply: { type: String, default: '*' },
    barometricPressure: { type: String, default: '*' },
    oilSupply: { type: String, default: '*' },
    threadNipper: { type: String, default: '*' },
    twoStepPresserFoot: { type: String, default: '*' },
    intermittentPressureRise: { type: String, default: '*' },
    intermittentPressureOnTheTrip: { type: String, default: '*' },
    speed: { type: String, default: '*' },
    compressedAir: { type: String, default: '*' },
    upperPressureWheelLiftDistance: { type: String, default: '*' },
    maxOveredgingWidth: { type: String, default: '*' },
    threadLine: { type: String, default: '*' },
    maxSewingThick: { type: String, default: '*' },
    needleStitchRange: { type: String, default: '*' },
    image: { type: String, default: '*' }
});

export default SpecialSeriesSubModelSchema;
